name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone 
        uses: GuillaumeFalourd/clone-github-repo-action@v2.3
        with:
          owner: 'jake-bot-discord'
          repository: 'Website'
          access-token: ${{ secrets.PAT_KEY }}